#!/usr/bin/env python3
"""Generate an offline catalog; requires the model outputs and CAD previews."""
from pathlib import Path
import json,html
ROOT=Path(__file__).resolve().parent

def main():
    products=json.loads((ROOT/'catalog.json').read_text())['products'];cards=[]
    for p in products:
        id=p['id'];arch=id.startswith(('04','05'));esc=html.escape
        stats=json.loads((ROOT/id/'validation.json').read_text())
        dims=' × '.join(f'{x:.2f}'.rstrip('0').rstrip('.') for x in stats['print_plate']['dimensions_mm'])+' mm'
        tabs=''
        if arch:tabs='<div class="tabs">'+''.join(f'<button data-src="{id}/{file}" aria-pressed="{str(i==0).lower()}">{label}</button>' for i,(file,label) in enumerate([('preview.png','Perspective'),('plan-view.png','Overhead'),('unpainted-preview.png','Unpainted')]))+'</div>'
        downloads=''.join(f'<a href="{id}/{file}" download>{label}</a>' for file,label in [('output_model.3mf','Print 3MF'),('output_model.stl','STL'),('output_model.step','STEP'),('model.py','Python source')])
        features=''.join('<li>'+esc(x)+'</li>' for x in p['features'])
        notice='<p class="notice">NON-CLINICAL DEMO · Not for patient or intraoral use.</p>' if id.startswith('06') else ''
        cards.append(f'''<article><div class="picture"><img src="{id}/preview.png" alt="{esc(p['title'])}: actual CAD geometry"></div><div class="body"><small>{esc(p['category'])}</small><h2>{esc(p['title'])}</h2>{tabs}<p>{esc(p['use'])}</p><b class="dimensions">Print layout: {dims} · {stats['parts']} printable part(s)</b><ul>{features}</ul>{notice}<nav>{downloads}</nav><details><summary>Printing & customization</summary><p>{esc(p['print'])}</p><p>Parameters: <code>{', '.join(p['customize'])}</code></p><p>{esc(p.get('hardware',''))}</p><p>{esc(p['limits'])}</p></details></div></article>''')
    page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>polukal / Architecture & industry catalog</title><style>
:root{--ink:#203b38;--muted:#526e65;--line:#cdd7cf;--paper:#f2f3ed;color-scheme:light}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.55 system-ui,-apple-system,sans-serif}a{color:inherit}header,main,footer{max-width:1440px;margin:auto;padding:32px 40px}.top{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--line);padding:10px 0 22px}.brand{font-size:30px;font-weight:750;letter-spacing:-1px}.edition,small{text-transform:uppercase;letter-spacing:1.5px;font-size:11px;color:var(--muted)}h1{font-size:clamp(34px,5vw,68px);line-height:1.08;letter-spacing:-2px;max-width:950px;margin:45px 0 22px}header>p{max-width:700px;font-size:19px;color:var(--muted)}.quick,nav,.tabs{display:flex;flex-wrap:wrap;gap:9px}.quick a,nav a{border:1px solid var(--line);border-radius:5px;text-decoration:none;padding:9px 13px;font-size:13px}.quick a:first-child,nav a:first-child{color:white;background:var(--ink);border-color:var(--ink)}main{padding-top:0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:28px}article{background:white;border:1px solid var(--line);border-radius:12px;overflow:hidden}.picture{aspect-ratio:1.38;background:#eceee8}.picture img{width:100%;height:100%;object-fit:contain;display:block}.body{padding:25px 28px}h2{font-size:27px;line-height:1.18;letter-spacing:-.7px;margin:11px 0 18px}.body p,ul{color:var(--muted)}ul{font-size:14px;padding-left:20px}.dimensions{font-size:13px}li{margin:6px 0}.tabs{margin:18px 0}.tabs button{font:inherit;font-size:12px;border:1px solid var(--line);border-radius:4px;padding:8px 10px;background:var(--paper);color:var(--muted);cursor:pointer}.tabs button[aria-pressed=true]{background:var(--ink);color:white}nav{margin:25px 0 18px}details{border-top:1px solid var(--line);padding-top:15px;font-size:13px}summary{font-weight:650;cursor:pointer}code{font-size:11px;overflow-wrap:anywhere}.notice{background:#f7ede1;border-left:3px solid #ba8050;padding:12px;font-size:12px;font-weight:650}footer{font-size:13px;color:var(--muted);padding-bottom:55px}footer p{max-width:900px}a:focus-visible,button:focus-visible,summary:focus-visible{outline:3px solid #ae7e38;outline-offset:3px}@media(max-width:780px){header,main,footer{padding-left:18px;padding-right:18px}.grid{grid-template-columns:1fr}.edition{max-width:140px;text-align:right}.body{padding:22px}h1{letter-spacing:-1.2px}}
</style></head><body><header><div class="top"><span class="brand">polukal</span><span class="edition">Parametric CAD / 06 models</span></div><h1>Architecture you can hold.<br>Landscapes you can explore.</h1><p>Two printable architectural scenes lead a collection of six editable models for design presentations, fabrication and product development.</p><div class="quick"><a href="polukal-industry-catalog.zip" download>Download catalog</a><a href="#printing">Print notes</a><a href="catalog-preview.png">All six previews</a></div></header><main><div class="grid">'''+''.join(cards)+'''</div></main><footer id="printing"><p><strong>Build locally:</strong> Install requirements.txt in a Python environment, then run <code>python build_all.py --previews</code>. Run each standalone <code>model.py</code> from its own folder to export <code>./output_model.stl</code>. Expand each product’s printing notes above for orientation, hardware and customization.</p><p>Previews are rendered from actual CAD geometry. Colors illustrate optional painting; print files contain single-material models. Default geometry has passed digital checks. Physical printing, hardware fits and application-specific tests remain pending.</p><p>All geometry uses millimeters. Each design includes a standalone Python generator. Generated CAD exports remain local and are excluded from Git clones; regenerate them using the root guide.</p></footer><script>for(const b of document.querySelectorAll('[data-src]'))b.addEventListener('click',()=>{const a=b.closest('article');a.querySelector('img').src=b.dataset.src;a.querySelector('img').alt=a.querySelector('h2').textContent+' — '+b.textContent;for(const t of a.querySelectorAll('[data-src]'))t.setAttribute('aria-pressed',String(t===b));});</script></body></html>'''
    (ROOT/'index.html').write_text(page);print(ROOT/'index.html')
if __name__=='__main__':main()
